services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: gestao-pedidos-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
    container_name: product-catalog-api
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      PORT: 4000
      SERVER_URL: http://localhost:4000
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    ports:
      - "4000:4000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:4000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  rabbitmq_data:
