sonar.projectKey=gestao-pedidos
sonar.organization=sua-organizacao-sonarcloud
sonar.projectName=GestaoPedidos
sonar.sources=src
sonar.tests=tests
sonar.exclusions=dist/**,node_modules/**,coverage/**,logs/**
sonar.test.inclusions=tests/**/*.test.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=src/server.ts,src/app/core/**,src/types/**
