global:
  scrape_interval: 15s

scrape_configs:
  - job_name: gestaopedidos-api
    metrics_path: /metrics
    scrape_interval: 15s
    static_configs:
      - targets:
          - gestaopedidos-api:5000
